const CryptoJS = require("crypto-js")

function get_params(return_time) {
    _0x2aea9b = [
        "\" style=\"left: ",
        "high",
        "<i></i>",
        "_hash",
        "BlockCipher",
        "init_rotate",
        "d_desc",
        "push",
        "_mode",
        "words",
        "localTime",
        "Inflate",
        "PasswordBasedCipher",
        "unshift",
        "avail_out",
        "clone",
        "token",
        "sin",
        "EMBED",
        "http",
        "max",
        "HTML_STRING",
        "match_available",
        "total",
        "nlen",
        "Word",
        "_des3",
        "white",
        "Arguments",
        "prev",
        "ECB",
        "NoPadding",
        "344%",
        "Cannot find module '",
        "Decryptor",
        "encrypt",
        "last_flush",
        "CBC",
        "Z_SYNC_FLUSH",
        "cx_moving",
        "click",
        "charAt",
        ".cx_hkinnerWrap",
        "exports",
        "invalid code -- missing end-of-block",
        "_lBlock",
        "padding",
        "originImage",
        "-65px",
        "Z_FINISH",
        "protocol",
        "url(\"",
        "Invalid code point",
        "clientY",
        "./utils/common",
        "match_length",
        "set",
        "lineJoin",
        "back",
        ".cx_tips__answer",
        "$super",
        "offsetLeft",
        "currentScript",
        "SLIDE_EVENT",
        "Buf8",
        "dyn_ltree",
        "createElement",
        "_tr_tally",
        "interactive",
        ".status-icon",
        "format",
        "190tWsQLf",
        "_data",
        "low",
        "html",
        "havedict",
        "incorrect length check",
        "pointer",
        "ajax",
        "verify_failed",
        "deflateReset",
        "algo",
        ".cx_tip_text",
        "cfg",
        "HMAC",
        "lens",
        "USE_LANGUAGE",
        "deflateInfo",
        "stream error",
        "#cx_imgBg",
        "_tr_stored_block",
        "_nDataBytes",
        "head",
        "prev_match",
        "_invSubKeys",
        "max_chain",
        "wsize",
        "SHA1",
        "RUN_ENV",
        ".u-layer",
        "btoa",
        "\" class=\"cx_icon-point cx_point-",
        "last",
        "clientWidth",
        "chunks",
        "shadeImage",
        "TouchEvent",
        "pako deflate (from Nodeca project)",
        "eJwFwaESQEAYhdFn2T9/Ya/dtciCImOMQEFRJGO8u3Neu62xKz+9y25f27E7pm0w7LRmlgjUKFGgghLhqcgoEpEnobB8P05ND/k=",
        "_createHmacHelper",
        ".cx_imgDrag",
        "get",
        "name",
        ".cx_icon-point",
        "string2buf",
        "6172288yjlKRA",
        "next",
        "x64",
        "offset",
        "Latin1",
        "MODULE_NOT_FOUND",
        "config",
        "amd",
        "header",
        "captcha/check/verification/result",
        "incompatible version",
        "apply",
        "encryptBlock",
        "deflate",
        "stack",
        "raw",
        "buf2string",
        "light.js?t=",
        "obstacle",
        "has_stree",
        "good_length",
        "./zlib/messages",
        "Encryptor",
        "bi_valid",
        "work",
        "./lib/zlib/constants",
        "onreadystatechange",
        "splice",
        "cx_click",
        "向右拖动滑块填充拼图",
        "init_text_click",
        "_tr_flush_block",
        "decrypt",
        ".cx_image_margin",
        "HmacSHA256",
        "4562365xsvyjd",
        ".cx_imgBtn",
        "_doCryptBlock",
        "constructor",
        "<b style=\"font-weight:bold;\">",
        "Utf16BE",
        "static_len",
        "px; top: ",
        "deflateSetHeader",
        "originalEvent",
        "2570334vEUchu",
        "HmacSHA1",
        "onData",
        "define",
        "hash_shift",
        "MD5",
        "length",
        "inflateEnd",
        "outputLength",
        "clientHeight",
        "hold",
        "_dict_set",
        "toString",
        "processBlock",
        "@@iterator",
        "coordinate",
        "static_tree",
        ".cx_fallback_tip",
        "onload",
        "Validation failed, please try again",
        "wnext",
        "status",
        "_xformMode",
        "distbits",
        "Cipher",
        "IS_TRUSTED",
        "after",
        "querySelector",
        "extra",
        "window_size",
        ".cx_max_error .cx_fallback_tip",
        "DES",
        "drop",
        "execute",
        "cx_max_error",
        "need dictionary",
        "inflateInit2",
        "wrap",
        "w_mask",
        "return",
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",
        "absolute",
        "attr",
        "<img src=",
        "Utf8",
        "depth",
        "undefined",
        "cx_rightBtnAni",
        "memLevel",
        "iconclick",
        "mixIn",
        "timeout",
        "random",
        "captcha/get/verification/image",
        "LIGHT",
        "max_lazy",
        "CHECK_CAPTCHA",
        "TEMPLATE_IMAGE_WIDTH",
        "hash_size",
        "flags",
        "stroke",
        "heap_len",
        "66262wmTVBl",
        "失败过多，点此重试",
        "status-success",
        "extra_len",
        "windowBits",
        "</div>",
        "gzhead",
        "4uJmZAq",
        "text",
        "拖动滑块，使图片角度为正",
        "_subKeys",
        "createDecryptor",
        "Please complete security verification",
        "./utils/strings",
        "Buf16",
        "sessionStorage",
        "distcode",
        "unknown compression method",
        "cx_imgBg",
        "CFB",
        "find",
        "pending_buf",
        "hcrc",
        "14px",
        "_tr_init",
        "./zlib/deflate",
        "CAPTCHA_SERVER",
        "Hasher",
        "https",
        "next_in",
        "show",
        "./crc32",
        "deg)",
        "result",
        "\"><div class=\"mode-img-status\"><div class=\"status-icon\"></div></div>",
        "Set",
        "_createHelper",
        "jsonp",
        "stacktrace",
        "cx_tips__answer_div",
        "addClass",
        "inflateGetHeader",
        "done",
        "script",
        "dmax",
        "Object",
        "verify_pass",
        "remove",
        "hash_mask",
        "onVerify",
        "round",
        "d_buf",
        "inflateSetDictionary",
        "getItem",
        "#52ccba",
        "cancelAnimationFrame",
        "<div num=\"",
        "avail_in",
        "sigBytes",
        "lineCap",
        "check",
        "match",
        "./lib/deflate",
        "hasOwnProperty",
        "SHA256",
        "inflateInit",
        "strstart",
        "320px",
        "__esModule",
        "captcha/obstacle.png",
        "mode-btn-slider",
        "PATH",
        "4114404bcgOiI",
        "cx_captcha_function",
        "RC4",
        "ndist",
        "was",
        "height",
        "touchstart",
        "arraySet",
        "cx_click_success",
        "invalid literal/length code",
        "rotate(",
        "36LfqqXo",
        "mousedown",
        "total_out",
        "DISTANCE",
        "CAPTCHA_MODE",
        "inflateReset2",
        "removeEventListener",
        "imageVerificationVo",
        "Malformed UTF-8 data",
        ".cx_modal_close",
        "cancelBubble",
        "good_match",
        "invalid window size",
        "max_chain_length",
        "invalid literal/lengths set",
        "object",
        "lenbits",
        "status-error",
        "slice",
        "en_",
        "CipherParams",
        "top",
        "65px",
        "mode-btn",
        "_oKey",
        "touchend",
        "_ENC_XFORM_MODE",
        "Map",
        "number",
        "embed",
        "update",
        "[object ArrayBuffer]",
        "Hex",
        "concat",
        "enc",
        "md5",
        "_counter",
        "getContext",
        "iterator",
        "none",
        "clearRect",
        "toX32",
        "clientX",
        "Iso10126",
        "deflateEnd",
        "exec",
        "serverTime",
        "mode",
        "_rBlock",
        "SHA224",
        "runEnv",
        "-10px",
        "TripleDES",
        "lencode",
        ".cx_refresh",
        "_prevBlock",
        "salt",
        "initCXCaptcha",
        "clamp",
        "prototype",
        "[native code]",
        "lookahead",
        "browserLocale",
        "stopPropagation",
        "l_buf",
        "callback",
        "#prompt",
        "Please click in order ",
        "event",
        "lendyn",
        "setItem",
        "extra_bits",
        "invalid stored block lengths",
        "_map",
        "async",
        "20px",
        "preventDefault",
        "./inffast",
        "hasClass",
        "OpenSSL",
        "hide",
        "_cipher",
        "362790XlTnkP",
        "css",
        "next_out",
        "requestAnimationFrame",
        "PBKDF2",
        "l_desc",
        "src",
        "sqrt",
        "flattenChunks",
        "display",
        "returnValue",
        "formatter",
        "_DEC_XFORM_MODE",
        "comment",
        "sourceURL",
        "changedTouches",
        "POPUP",
        "strokeStyle",
        "SHA3",
        "bl_tree",
        "-145px",
        "./zlib/inflate",
        ".cx_imgBg",
        "SerializableCipher",
        "lib",
        "shrinkBuf",
        "level",
        "160px",
        "deflateInit2",
        "isTrusted",
        "inflateResetKeep",
        "_process",
        "hasher",
        "mouseup",
        "location",
        "_doProcessBlock",
        "buffer error",
        "./lib/inflate",
        "HmacSHA224",
        "relative",
        "onerror",
        "text/javascript",
        "join",
        "</b>",
        "Too many failures, click Retry",
        "filter",
        "setTyped",
        "substr",
        "max_lazy_match",
        "_minBufferSize",
        "./zlib/zstream",
        "请依次点击 ",
        "atob",
        "reset",
        "OBSTACLE",
        "xflags",
        "_keystream",
        "ungzip",
        "Z_BUF_ERROR",
        "readyState",
        "stat_desc",
        "extend",
        "offsetX",
        "<div class=\"u-opacity\"></div><div class=\"u-captcha u-layer\" id=\"eject\">",
        "Deflate",
        "Utf16LE",
        "cx_imgDrag",
        "msg",
        "_keySchedule",
        "gzip",
        "ciphertext",
        "key",
        "beginPath",
        "last_lit",
        "_key",
        "HmacRIPEMD160",
        "Rabbit",
        "pending",
        "0123456789abcdef",
        "subarray",
        "bits",
        "lineWidth",
        "prev_length",
        "touches",
        "total_in",
        "stringify",
        "pow",
        "RabbitLegacy",
        "deflateRaw",
        "ncode",
        "HmacSHA512",
        "#f57a7a",
        "invalid distance code",
        "lit_bufsize",
        "ins_h",
        "err",
        "_parse",
        "halfDv",
        "whave",
        "验证通过",
        "binstring2buf",
        "removeClass",
        "GET_SERVER_TIME",
        "background",
        "decode",
        ".cx_max_error .cx_refresh",
        "FZDBSJW",
        "inflate",
        "TEXT_CLICK",
        "ended",
        "54507134jqmXVQ",
        "language",
        "extraData",
        "TextEncoderLite",
        "img",
        ".cx_rightBtn",
        "验证失败，请重试",
        "w_size",
        "options",
        "Validation passed",
        "HmacSHA384",
        "finalize",
        "BlockCipherMode",
        "block",
        "data_type",
        "ZeroPadding",
        "./zlib/constants",
        "loaded",
        "call",
        "cx_error",
        "cx_icon_error",
        "_invKeySchedule",
        "Base",
        "have",
        "charCodeAt",
        "max_code",
        "getElementsByTagName",
        "compute",
        "decryptBlock",
        "mousemove",
        "ICON_CLICK",
        "gzindex",
        "w_bits",
        "://",
        "AES",
        "window",
        "./lib/utils/common",
        "hash_bits",
        "IMAGE_VERIFY_TAG",
        "#45494c",
        "fromCharCode",
        "./adler32",
        "assign",
        "#fff url(\"",
        "dictionary",
        "blockSize",
        "floor",
        "cx_success",
        "string",
        "RC4Drop",
        "chunkSize",
        "insert",
        "pad",
        "captcha/get/conf",
        "_iKey",
        "14ffpIeA",
        "addEventListener",
        "cx_obstacle_canvas",
        "extra_base",
        "time",
        "default",
        "onEnd",
        "#fff url(",
        "_doReset",
        "SHA384",
        "CAPTCHA_TYPE",
        "_append",
        "OFB",
        "cx_success_refresh",
        "off",
        "strm",
        "dyn_tree",
        "max_length",
        "Base64",
        "initCXCaptcha requires a window with a document",
        ".u-opacity",
        "invalid distances set",
        "nice_length",
        "isArray",
        "Pkcs7",
        "style",
        "file error",
        "type",
        "lineTo",
        "heap",
        "84px",
        "RIPEMD160",
        "create",
        "sane",
        "stream end",
        "bi_buf",
        "getBoundingClientRect",
        "min",
        "cx_image_margin",
        "init",
        "pending_buf_size",
        "inline-block",
        "width",
        "too many length or distance symbols",
        "TextDecoderLite",
        "dyn_dtree",
        "createEvent",
        "method",
        "17px",
        "clickArr",
        "END_EVENT",
        "output",
        "cookie",
        "elems",
        "HmacSHA3",
        "heap_max",
        "hidden",
        "replace",
        "WordArray",
        "GET_CAPTCHA",
        "test",
        "pending_out",
        "MOVE_EVENT",
        "_hasher",
        "_iv",
        "px;\"></div>",
        "strategy",
        "offsetY",
        "substring",
        "nice_match",
        "context",
        "Z_OK",
        "Z_NEED_DICT",
        "document",
        "invalid bit length repeat",
        "createEncryptor",
        "../utils/common",
        "init_icon_click",
        "StreamCipher",
        "./messages",
        "./trees",
        "kdf",
        "140px",
        "0px",
        "ivSize",
        "input",
        "adler",
        "opt_len",
        "touchmove",
        "BufferedBlockAlgorithm",
        "OBSTACLE_IMAGE",
        "matches",
        "deflateResetKeep",
        "START_EVENT",
        "textclick",
        "split",
        "EvpKDF",
        "_nRounds",
        "getTime",
        "match_start",
        "getAttribute",
        "wbits",
        "max_error",
        "distdyn",
        "_des2",
        "utf8border",
        "block_start",
        "buf2binstring",
        "invalid distance too far back",
        "_state",
        "SHA512",
        "_doFinalize",
        "keySize",
        "pop",
        "symbol",
        "offsetTop",
        "inflateReset",
        "CALLBACK_NAME",
        "SLIDE",
        "BUTTON_IMAGE_WIDTH",
        "left",
        "请完成安全验证",
        "indexOf",
        "scripts",
        "_tr_align",
        "ROTATE",
        "bl_desc",
        "insufficient memory",
        "ceil",
        "func",
        "bl_count",
        "message",
        "state",
        "now",
        "verifyResult",
        "code",
        "href",
        "Buf32",
        "Z_STREAM_END",
        "incorrect data check",
        "unpad",
        "eJyrVipWslIyDzHxC3MyMw3NTcuoUHRNUtJRylSyijbTMTTVMdAx1THUMTTWMdax0DHXMdIx0TE00jEEkkBRAx3L2FoARFQPzw==",
        "version",
        "appendChild",
        "./inftrees",
        "parse",
        "function",
        "getElementById",
        "_des1",
        "moveTo"
    ]
    const captchaId = "GcXX5vewqE7DezKGlyvleKCnkTglvGpL"

    function _0x2e675c(_0x87802b, _0x5ef299) {
        _0x87802b = _0x87802b - 0x128;
        var _0x2d8418 = _0x2aea9b[_0x87802b];
        return _0x2d8418;
    }

    function _0x11dbad() {
        var _0x5c52a4 = _0x2e675c;
        for (var _0x55977e = [], _0x12474f = _0x5c52a4(0x2f9), _0x33c6e8 = 0x0; _0x33c6e8 < 0x24; _0x33c6e8++)
            _0x55977e[_0x33c6e8] = _0x12474f['substr'](Math['floor'](0x10 * Math[_0x5c52a4(0x1fc)]()), 0x1);
        return _0x55977e[0xe] = '4',
            _0x55977e[0x13] = _0x12474f[_0x5c52a4(0x2da)](0x3 & _0x55977e[0x13] | 0x8, 0x1),
            _0x55977e[0x8] = _0x55977e[0xd] = _0x55977e[0x12] = _0x55977e[0x17] = '-',
            _0x55977e[_0x5c52a4(0x2d5)]('');
    }

    const captchaKey = CryptoJS.MD5(return_time + _0x11dbad()).toString()
    const token = CryptoJS.MD5(return_time + captchaId + "slide" + captchaKey) + ':' + (parseInt(return_time) + 300000).toString()
    const iv = CryptoJS.MD5(captchaId + "slide" + Date.now() + _0x11dbad()).toString();

    data_params = {
        'captchaKey': captchaKey,
        'token': token,
        'iv': iv
    }
    console.log(data_params);
    return data_params
}

function encryptByAES(message) {
    const key = "u2oh6Vu^HWe4_AES"
    let CBCOptions = {
        iv: CryptoJS.enc.Utf8.parse(key),
        mode: CryptoJS.mode.CBC,
        padding: CryptoJS.pad.Pkcs7
    };
    let aeskey = CryptoJS.enc.Utf8.parse(key);
    let secretData = CryptoJS.enc.Utf8.parse(message);
    let encrypted = CryptoJS.AES.encrypt(
        secretData,
        aeskey,
        CBCOptions
    );
    return CryptoJS.enc.Base64.stringify(encrypted.ciphertext);
}

function get_encrypt_param(strdata) {
    message = strdata
    data = encodeURIComponent(encryptByAES(message))
    console.log(data);
    return data
}
